### PR TITLE
Fix member adding and removing issue

### LINKED ISSUE #17: Cordinator node keeps trying to connect to destroyed pods
**Description:**
When a pod is destroyed in a two node cluster, the cordinator nodes keep trying to connect to the destroyed pods IP address. This results in connection refused error as follows. The error occurs only in debug mode for hazelcast clustering.

`[2019-04-03 05:12:13,558] DEBUG {com.hazelcast.nio.tcp.SocketConnector} -  [172.31.41.64]:4000 [wso2.is.domain] [3.5.4] Connection timed out to address /172.31.1.116:4001
java.net.SocketException: Connection timed out to address /172.31.1.116:4001
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at com.hazelcast.nio.tcp.SocketConnector.connectSocketChannel(SocketConnector.java:157)
	at com.hazelcast.nio.tcp.SocketConnector.tryToConnect(SocketConnector.java:132)
	at com.hazelcast.nio.tcp.SocketConnector.run(SocketConnector.java:68)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

**Affected Product Version:**
All products

**Steps to reproduce:**
1. Enable debug logs for log4j.logger.com.hazelcast in the log4j.properties file
2. Delete a pod and check for the logs

**Related Issues:**

### PR DESCRIPTION
**Pull request by ctienshi**
## Automation tests
N/A

### CODE REVIEW

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java [hunk 1]
```diff
@@ -150,13 +154,16 @@ private Parameter getParameter(String name) {
             } catch (InterruptedException ignored) {
             }
             HazelcastUtil.sendMessagesToMember(messageBuffer, member, carbonCluster);
+            log.info(String.format("Current member list: %s", nwConfig.getJoin().getTcpIpConfig().setEnabled(true).getMembers()));
```
Comment (rushmin) [inline kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: Check log.isInfoEnabled as a string format operation is used inside log.info()

Comment (ctienshi) [reply kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: Fixed with d72688e851a9b9f9f2a32888b2766eb42533046a

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java [hunk 2]
```diff
@@ -139,6 +139,11 @@ private Parameter getParameter(String name) {
 
         @Override public void memberAdded(MembershipEvent membershipEvent) {
             Member member = membershipEvent.getMember();
+            List<String> memberList = nwConfig.getJoin().getTcpIpConfig().setEnabled(true).getMembers();
```
Comment (afkham) [inline kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: .setEnabled(true) is not needed. 

TcpIpConfig tcpIpConfig = nwConfig.getJoin().getTcpIpConfig();
List<String> memberList = tcpIpConfig.getMembers();

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java [hunk 3]
```diff
@@ -139,6 +139,11 @@ private Parameter getParameter(String name) {
...
+            if (!memberList.contains(member.getSocketAddress().getAddress().getHostAddress())) {
+                nwConfig.getJoin().getTcpIpConfig().setEnabled(true)
+                        .addMember(String.valueOf(member.getSocketAddress().getAddress().getHostAddress()));
```
Comment (afkham) [inline kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: tcpIpConfig.addMember(String.valueOf(member.getSocketAddress().getAddress().getHostAddress()));

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java [hunk 4]
```diff
@@ -150,13 +155,23 @@ private Parameter getParameter(String name) {
             } catch (InterruptedException ignored) {
             }
             HazelcastUtil.sendMessagesToMember(messageBuffer, member, carbonCluster);
+            if (log.isInfoEnabled()) {
+                log.info(String.format("Current member list: %s",
+                        nwConfig.getJoin().getTcpIpConfig().setEnabled(true).getMembers()));
```
Comment (afkham) [inline kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: tcpIpConfig.getMembers()

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java [hunk 5]
```diff
@@ -150,13 +155,23 @@ private Parameter getParameter(String name) {
             } catch (InterruptedException ignored) {
             }
             HazelcastUtil.sendMessagesToMember(messageBuffer, member, carbonCluster);
+            if (log.isInfoEnabled()) {
```
Comment (afkham) [inline kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: log.isDebugEnabled

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java [hunk 6]
```diff
@@ -150,13 +155,23 @@ private Parameter getParameter(String name) {
...
+                        nwConfig.getJoin().getTcpIpConfig().setEnabled(true).getMembers()));
+            }
         }
 
         @Override public void memberRemoved(MembershipEvent membershipEvent) {
             Member member = membershipEvent.getMember();
             carbonCluster.memberRemoved(member);
             log.info(String.format("Member left: [UUID] %s, [Address] %s", member.getUuid(),
                     member.getSocketAddress().toString()));
+            nwConfig.getJoin().getTcpIpConfig().setEnabled(true)
```
Comment (afkham) [inline kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: WRONG!!! I clearly explained that you need to call the k8s API server, and get the list of pods and see whether that member has lost. This change will cause members to not rejoin after a temporary network glitch.

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java (hunk 2 above)
Comment (ctienshi) [reply kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: fixed with 7913ee0074c4ebbc8590adf1013ffb6eea5efee6

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java (hunk 3 above)
Comment (ctienshi) [reply kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: fixed with 7913ee0074c4ebbc8590adf1013ffb6eea5efee6

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java (hunk 4 above)
Comment (ctienshi) [reply kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: fixed with 7913ee0074c4ebbc8590adf1013ffb6eea5efee6

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java (hunk 5 above)
Comment (ctienshi) [reply kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: fixed with 7913ee0074c4ebbc8590adf1013ffb6eea5efee6

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java (hunk 6 above)
Comment (ctienshi) [reply kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: fixed with 7913ee0074c4ebbc8590adf1013ffb6eea5efee6

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java [hunk 7]
```diff
@@ -68,42 +70,66 @@ public KubernetesMembershipScheme(Map<String, Parameter> parameters, String prim
...
+    /**
+     * Retrieves the set of IP addresses of the current PODs in the K8S cluster, using K8S API server or the DNS.
+     * The returned set may contain the IP address of the pod running this JVM.
+     *
+     * The IP address resolver will use DNS lookup if "USE_DNS" environment property is set. Otherwise it uses K8S
+     * API server, to retrive the IP addresses.
+     *
+     * @return IP addresses of the current pods. Returns null upon any error querying K8S.
+     */
+
```
Comment (afkham) [inline kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: Remove empty line

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java [hunk 8]
```diff
@@ -68,42 +70,66 @@ public KubernetesMembershipScheme(Map<String, Parameter> parameters, String prim
...
+        } else {
+            return Collections.emptySet();
+        }
+    }
+
+    /**
+     * Initiates the Pod IP resolver.
+     * Uses the DNS based pod IP resolver or the API based pod IP resolver.
+     */
+
```
Comment (afkham) [inline kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: Remove empty line

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java (hunk 7 above)
Comment (ctienshi) [reply kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: fixed with d5378b70c1173a539a9bf725b9d6e8e3efa332da

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java (hunk 8 above)
Comment (ctienshi) [reply kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: fixed with d5378b70c1173a539a9bf725b9d6e8e3efa332da

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java [hunk 9]
```diff
@@ -68,42 +70,64 @@ public KubernetesMembershipScheme(Map<String, Parameter> parameters, String prim
...
-                podIpResolver = new DNSBasedPodIpResolver(parameters);
-            } else {
-                log.debug("Using API based pod ip resolving method");
-                podIpResolver = new ApiBasedPodIpResolver(parameters);
-            }
-            containerIPs = podIpResolver.resolveAddresses();
+            initPodIpResolver();
+            Set <String> containerIPs = getK8sPodIpAddresses();
             // if no IPs are found, can't initialize clustering
             if (containerIPs.isEmpty()) {
```
Comment (afkham) [inline kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: Can this happen? If this member (local member) is running, it means there should be at least one pod. Anyway there is no harm in having this condition.

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java [hunk 10]
```diff
@@ -68,42 +70,64 @@ public KubernetesMembershipScheme(Map<String, Parameter> parameters, String prim
...
                 throw new KubernetesMembershipSchemeException("No member ips found, unable to initialize the "
```
Comment (afkham) [inline kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: No members found. Not no member ips found. Anyway, it should have been IPs not ips

Comment (ctienshi) [reply kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: Fixed with a3dc589517dfbc10315480e547af8f19299566bb

File: kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java (hunk 9 above)
Comment (ctienshi) [reply kubernetes-membership-scheme/src/main/java/org/wso2/carbon/membership/scheme/kubernetes/KubernetesMembershipScheme.java]: Yes. Since there is already a pod running the IP list wouldn't be empty.
